{application,mochiwebdemo,
             [{description,"mochiwebdemo"},
              {vsn,"0.1"},
              {modules,[mochiwebdemo,mochiwebdemo_app,mochiwebdemo_deps,
                        mochiwebdemo_sup,mochiwebdemo_web]},
              {registered,[]},
              {mod,{mochiwebdemo_app,[]}},
              {env,[]},
              {applications,[kernel,stdlib,crypto]}]}.
